apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc_name }}
spec:
  storageClassName: {{ .Values.pvc_storageClassName }}
  accessModes:
    - {{ .Values.pvc_accessModes }}
  resources:
    requests:
      storage: "{{ .Values.pvc_capacity }}"