apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod1_name }}
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.pod1_image.repository }}:{{ .Values.pod1_image.tag }}
        ports:
        - containerPort: {{ .Values.pod1_port }}
