apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod2_name }}
  labels:
    app: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: {{ .Values.pod2_image.repository }}:{{ .Values.pod2_image.tag }}
        ports:
        - containerPort: {{ .Values.pod1_port }}
