apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.pod3_name }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.pod3_service1.name }}
            port:
              number: {{ .Values.pod3_port }}
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.pod3_service2.name }}
            port:
              number: {{ .Values.pod3_port }}           
