apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod4_name }}
spec:
  type: {{ .Values.pod4_type }}
  selector:
    app: {{ .Values.pod4_app }}
  ports:
    - protocol: {{ .Values.pod4_protocol }}
      port: {{ .Values.pod4_port }}
      targetPort: {{ .Values.pod4_targetPort }}
      nodePort: {{ .Values.pod4_nodePort }}
