apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod5_name }}
spec:
  selector:
    app: {{ .Values.pod5_name }}
  ports:
    - protocol: {{ .Values.pod4_protocol }}
      port: {{ .Values.pod4_port }}
      targetPort: {{ .Values.pod4_targetPort }}
      nodePort: {{ .Values.pod5_nodePort }}
