apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod5_name }}
spec:
  selector:
    type: {{ .Values.pod5_type }}
    app: {{ .Values.pod5_name }}
  ports:
    - protocol: {{ .Values.pod4_protocol }}
      port: {{ .Values.pod4_port }}
      targetPort: {{ .Values.pod4_targetPort }}
      
      
